# Generated by Django 3.2.3 on 2021-05-31 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('call', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('pwd', models.CharField(max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_4_digit', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_name', to='kkuuk.store')),
            ],
        ),
        migrations.CreateModel(
            name='Histroy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trade_type', models.CharField(choices=[('save', '적립'), ('use', '사용')], max_length=5)),
                ('trade_at', models.DateTimeField(auto_now_add=True)),
                ('before_stamp', models.IntegerField(default=0)),
                ('val_stamp', models.IntegerField(default=0)),
                ('after_stamp', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='kkuuk.user')),
            ],
        ),
    ]
