# Generated by Django 3.2.3 on 2021-06-04 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kkuuk', '0002_user_is_deleted'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Histroy',
            new_name='History',
        ),
    ]
